language: go

go:
  - "1.12"

os:
  - linux

dist: trusty
sudo: false
install: true

script:
  - unset GOPATH
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  
after_success:
  - bash <(curl -s https://codecov.io/bash)  
